---
# Source: internal-service/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: internal-service-internal-service
spec:
  type: ClusterIP
  selector:
    app: internal-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
# Source: internal-service/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: internal-service-internal-service
  labels:
    app: internal-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: internal-service
  template:
    metadata:
      labels:
        app: internal-service
    spec:
      containers:
        - name: app
          image: "tigranham/nxlog-env-app:latest"
          ports:
            - containerPort: 8080
          env:
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            runAsUser: 1000
---
# Source: internal-service/templates/hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: internal-service-internal-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: internal-service-internal-service
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
