apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: internal-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Tigranhambardzumyan/nxlog-devops-assignment
    targetRevision: development
    path: gitops/overlay
  destination:
    server: https://kubernetes.default.svc
    namespace: internal-service
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
