apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "internal-service.fullname" . }}
  labels:
    app: {{ include "internal-service.name" . }}
spec:
  replicas: {{ .Values.replicaCount | default 3 }}
  selector:
    matchLabels:
      app: {{ include "internal-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "internal-service.name" . }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.hub }}/{{ .Values.image }}:{{ .Values.tag }}"
          ports:
            - containerPort: 8080
          env:
            {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: "{{ $val }}"
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            runAsUser: 1000
